### ISSUE TITLE
How to Run?

### ISSUE THREAD

**Issue by bhralz** [canxkoz/Multiple-Face-Recognition#1]
Dear Can Koz
please support step by step procedure how to run the code.
Thanks for your replying.

**Comment by canxkoz** [comment]
You should run the code that I indicate as in the readme file from top to bottom. I am rewriting the steps so that you can fork my project and possibly improve it.
1)download all the packages, if you are not using pycharm ide, it is going to be harder for you to find the specific packages because setting up Keras OpenCV and Tensorflow are hard tasks in various operating systems.
2)run build_dataset and take 40-50 pictures of your face by clicking the indicated button to take pictures. You must create a file for yourself with your name on build_dataset.py
3)Create another file and take 40-50 pictures of your friend. You must create a file for the other person on build_dataset.py, and please pay attention to the directory that you create that file. The files should be within the project
4)run train_data.py and wait until the process is completed
5)Now, you can run Check Result and Real Time Re to actually see the computer seeing the difference between you and your friend!
